name: cursor_tool_ui
description: "Samlet værktøj til Cursor AI IDE med både CLI og GUI funktionalitet"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  path: ^1.8.0
  path_provider: ^2.0.14
  process_run: ^0.12.5
  sqlite3: ^1.9.0
  file_picker: ^5.2.5
  intl: ^0.18.1
  shared_preferences: ^2.0.20
  flutter_markdown: ^0.6.18
  args: ^2.3.0
  dart_console: ^1.1.0
  collection: ^1.16.0
  crypto: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 